#!/bin/bash
# Set up a forked-mainnet anvil environment for end-to-end multi-rollup testing.
#
# Assumes anvil is already running at http://127.0.0.1:8545 forking mainnet.
# Generates atp-indexer/.env and staking-dashboard/.env pointing at the local
# anvil + local indexer, then seeds sequencer rewards for the target address
# on every rollup the Registry has ever made canonical.
#
# Usage:
#   bash staking-dashboard/scripts/multi-rollup-test/setup-fork.sh
#
# Env overrides:
#   TARGET_ADDRESS   address to seed rewards for (default: anvil account 0)
#   RPC_URL          anvil RPC URL (default: http://127.0.0.1:8545)
#   INDEXER_PORT     port for the indexer API (default: 42068)

set -eu

ROOT=$(git rev-parse --show-toplevel)
INDEXER=$ROOT/atp-indexer
DASHBOARD=$ROOT/staking-dashboard
ADDRS_FILE=$INDEXER/contract_addresses.json

TARGET_ADDRESS="${TARGET_ADDRESS:-0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266}"
RPC_URL="${RPC_URL:-http://127.0.0.1:8545}"
INDEXER_PORT="${INDEXER_PORT:-42068}"

source "$ROOT/scripts/logging.sh"

# ---------- 1. Verify anvil ----------
log_step "Checking anvil at $RPC_URL..."
ANVIL_CHAIN_ID=$(cast chain-id --rpc-url "$RPC_URL" 2>/dev/null || echo "")
if [ -z "$ANVIL_CHAIN_ID" ]; then
  echo "Error: could not reach anvil at $RPC_URL"
  exit 1
fi
if [ "$ANVIL_CHAIN_ID" != "1" ]; then
  echo "Error: anvil chain id is $ANVIL_CHAIN_ID, expected 1 (mainnet fork)."
  echo "Restart anvil with: anvil --fork-url \$MAINNET_RPC --fork-block-number <pinned-block>"
  exit 1
fi
ANVIL_BLOCK=$(cast block-number --rpc-url "$RPC_URL")
log_success "  anvil OK: chain $ANVIL_CHAIN_ID @ block $ANVIL_BLOCK"

# ---------- 2. Validate addresses file ----------
if [ ! -f "$ADDRS_FILE" ]; then
  echo "Error: $ADDRS_FILE not found"
  exit 1
fi

ATP_FACTORY=$(jq -r '.atpFactory' "$ADDRS_FILE")
ATP_FACTORY_AUCTION=$(jq -r '.atpFactoryAuction' "$ADDRS_FILE")
ATP_FACTORY_MATP=$(jq -r '.atpFactoryMatp' "$ADDRS_FILE")
ATP_FACTORY_LATP=$(jq -r '.atpFactoryLatp' "$ADDRS_FILE")
ATP_REGISTRY=$(jq -r '.atpRegistry' "$ADDRS_FILE")
ATP_REGISTRY_AUCTION=$(jq -r '.atpRegistryAuction' "$ADDRS_FILE")
STAKING_REGISTRY=$(jq -r '.stakingRegistry' "$ADDRS_FILE")
REGISTRY=$(jq -r '.registryAddress' "$ADDRS_FILE")
ATP_FACTORY_BLOCK=$(jq -r '.atpFactoryDeploymentBlock' "$ADDRS_FILE")
REGISTRY_BLOCK=$(jq -r '.registryDeploymentBlock' "$ADDRS_FILE")
ATP_STAKER=$(jq -r '.atpWithdrawableAndClaimableStaker' "$ADDRS_FILE")
GENESIS_SALE=$(jq -r '.genesisSequencerSale' "$ADDRS_FILE")
GOVERNANCE=$(jq -r '.governanceAddress' "$ADDRS_FILE")
GSE=$(jq -r '.gseAddress' "$ADDRS_FILE")

# ---------- 3. Write atp-indexer/.env ----------
log_step "Writing $INDEXER/.env (start blocks pinned to mainnet deployment)..."
[ -f "$INDEXER/.env" ] && cp "$INDEXER/.env" "$INDEXER/.env.pre-fork"
cat > "$INDEXER/.env" <<EOF
# Generated by scripts/multi-rollup-test/setup-fork.sh
POSTGRES_CONNECTION_STRING=

RPC_URL=$RPC_URL
CHAIN_ID=1

ATP_FACTORY_ADDRESS=$ATP_FACTORY
ATP_FACTORY_AUCTION_ADDRESS=$ATP_FACTORY_AUCTION
ATP_FACTORY_MATP_ADDRESS=$ATP_FACTORY_MATP
ATP_FACTORY_LATP_ADDRESS=$ATP_FACTORY_LATP
STAKING_REGISTRY_ADDRESS=$STAKING_REGISTRY
REGISTRY_ADDRESS=$REGISTRY

# Pin start blocks to mainnet deployment so Ponder doesn't try to walk genesis.
START_BLOCK=$ATP_FACTORY_BLOCK
REGISTRY_START_BLOCK=$REGISTRY_BLOCK

PORT=$INDEXER_PORT

NODE_ENV=development
LOG_LEVEL=info
EOF

# ---------- 4. Write staking-dashboard/.env ----------
log_step "Writing $DASHBOARD/.env (RPC pointed at local anvil)..."
[ -f "$DASHBOARD/.env" ] && cp "$DASHBOARD/.env" "$DASHBOARD/.env.pre-fork"
cat > "$DASHBOARD/.env" <<EOF
# Generated by scripts/multi-rollup-test/setup-fork.sh
VITE_CHAIN_ID=1
VITE_RPC_URL=$RPC_URL
VITE_API_HOST=http://localhost:$INDEXER_PORT
VITE_EXPLORER_URL=https://etherscan.io
VITE_VALIDATOR_DASHBOARD_URL=https://dashtec.xyz
VITE_WALLETCONNECT_PROJECT_ID=

VITE_ATP_FACTORY_ADDRESS=$ATP_FACTORY
VITE_ATP_FACTORY_AUCTION_ADDRESS=$ATP_FACTORY_AUCTION
VITE_ATP_REGISTRY_ADDRESS=$ATP_REGISTRY
VITE_ATP_REGISTRY_AUCTION_ADDRESS=$ATP_REGISTRY_AUCTION
VITE_STAKING_REGISTRY_ADDRESS=$STAKING_REGISTRY
VITE_ATP_NON_WITHDRAWABLE_STAKER_ADDRESS=$ATP_STAKER
VITE_ATP_WITHDRAWABLE_STAKER_ADDRESS=$ATP_STAKER
VITE_ATP_WITHDRAWABLE_AND_CLAIMABLE_STAKER_ADDRESS=$ATP_STAKER
VITE_GENESIS_SEQUENCER_SALE_ADDRESS=$GENESIS_SALE
VITE_GOVERNANCE_ADDRESS=$GOVERNANCE
VITE_GSE_ADDRESS=$GSE

NODE_ENV=development
EOF

# ---------- 5. Seed rewards ----------
log_step "Seeding sequencer rewards via anvil_setStorageAt..."
cd "$ROOT"
TARGET_ADDRESS="$TARGET_ADDRESS" RPC_URL="$RPC_URL" \
  npx tsx "$DASHBOARD/scripts/multi-rollup-test/seed-fork.ts"

# ---------- 6. Next steps ----------
log_success ""
log_success "Setup complete. To run the stack:"
echo ""
echo "  Terminal 2 (indexer):"
echo "    cd $INDEXER && yarn install && yarn dev"
echo ""
echo "  Terminal 3 (dashboard):"
echo "    cd $DASHBOARD && yarn install && yarn dev"
echo ""
echo "After indexer catches up past block $REGISTRY_BLOCK, the dashboard's"
echo "/api/rollups call will succeed. The localStorage snippet above pre-fills"
echo "the saved coinbase address so the rewards section is populated immediately."
echo ""
echo "Re-running just the seed (e.g. after anvil reset):"
echo "  npx tsx $DASHBOARD/scripts/multi-rollup-test/seed-fork.ts"
